<a href="https://colab.research.google.com/github/Abhijith1825/NumPy-Activity/blob/main/Numpy_Activities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array with values from 10 to 49 (inclusive).

● Reshape it into a 4x10 matrix.

● Then extract the last column from the reshaped matrix

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
arr=np.arange(10,50).reshape(4,10)
arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[:,9]

array([19, 29, 39, 49])

2. Create two 3×3 matrices:

One filled with all 5s , One with values from 1 to 9

● Add the two matrices

● Multiply them element-wise

● Then find the transpose of the result

In [ ]:
x=np.array([[5,5,5],
           [5,5,5],
           [5,5,5]])
y=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print('x:',x)
print('y:',y)


x: [[5 5 5]
 [5 5 5]
 [5 5 5]]
y: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matrix_sum=x+y
matrix_sum

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
mul=x*y
mul

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
np.transpose(mul)

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

3. Create a NumPy array of 15 random integers between 10 and 100.

● Replace all values greater than 50 with -1

● Count how many values were replaced.

In [ ]:
Arr=np.random.randint(10,100,15)
Arr

array([43, 90, 22, 23, 46, 33, 12, 15, 84, 99, 96, 10, 32, 93, 97])

In [ ]:
Arr[Arr>50]=-1
Arr

array([43, -1, 22, 23, 46, 33, 12, 15, -1, -1, -1, 10, 32, -1, -1])

In [ ]:
count=np.sum(Arr==-1)
count

np.int64(6)

 Generate a 5×4 array with random values between 0 and 1 (float).

● Find the row with the maximum sum of values.

● Normalize each row using the formula: ----------------------------------------------------------------------------------------

In [ ]:
B=np.random.rand(5,4)
B

array([[0.01432446, 0.51196015, 0.16245228, 0.37943558],
       [0.48235315, 0.64585786, 0.38738131, 0.42359902],
       [0.36475335, 0.95396969, 0.78509609, 0.90769654],
       [0.46518453, 0.20005042, 0.19740491, 0.7753864 ],
       [0.61318017, 0.63666084, 0.64784983, 0.29670113]])

In [ ]:
row_sum = np.sum(B,axis=1)
max_row_index = np.argmax(row_sum)
max_row = B[max_row_index]
print(max_row)

[0.36475335 0.95396969 0.78509609 0.90769654]


In [ ]:
x = B
min_value = np.min(x,axis=1,keepdims=True)
max_value = np.max(x,axis=1,keepdims=True)
x_normalized = (x-min_value)/(max_value-min_value)
x_normalized


array([[0.        , 1.        , 0.29766317, 0.7336916 ],
       [0.36742925, 1.        , 0.        , 0.1401199 ],
       [0.        , 1.        , 0.71339287, 0.92146662],
       [0.46330137, 0.00457716, 0.        , 1.        ],
       [0.90126788, 0.96813604, 1.        , 0.        ]])

5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

● Find all unique elements

● Find the duplicates (elements that appear more than once) -----------------------------------------------------------------------------------------------

In [ ]:
arr = np.array([1,3,5,3,7,9,1,5,5])
unique,counts = np.unique(arr,return_counts=True)
duplicates = unique[counts>1]
print("Unique Elements:",unique)
print("Duplicates:",duplicates)


Unique Elements: [1 3 5 7 9]
Duplicates: [1 3 5]


6. Create a 6×6 NumPy array with values from 1 to 36.

● Extract the middle 4×4 submatrix.

● Then extract all even numbers from this submatrix.

In [ ]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
sub_matrix = arr[1:5, 1:5]
sub_matrix

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [ ]:
even_numbers = sub_matrix[sub_matrix%2==0]
even_numbers

array([ 8, 10, 14, 16, 20, 22, 26, 28])

7. Generate an array of shape (3, 4) with values from 0 to 11.

● Reshape it to (2, 6)

● Then flatten it into a 1D array

● Convert the 1D array back to shape (4, 3)

In [ ]:
arr=np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr_1=arr.reshape(2,6)
arr_1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
arr_2=arr_1.reshape(4,3)
arr_2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

8 . Create an array: a = np.array([[1, 2], [3, 4]])

● Append a new row [5, 6]

● Then append a new column [7, 8, 9]

In [ ]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.append(a,[[5,6]],axis=0)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c = np.append(b,[[7],[8],[9]],axis=1)
c

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.array([7, 8, 9])

● Join them into a single array

● Reshape the result into a 3×3 matrix

● Extract the diagonal elements

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
join = np.concatenate((a,b,c))
print("Joined_array:",join)

Joined_array: [1 2 3 4 5 6 7 8 9]


In [ ]:
matrix = join.reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
diagonal = np.diagonal(matrix)
diagonal

array([1, 5, 9])

10. Create a NumPy array of integers from 1 to 20.

● Extract all values that are divisible by 3 or 5.

● Count how many such values exist.

In [ ]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
Values = arr[(arr%3==0) | (arr%5==0)]
Values

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20])

In [ ]:
count=len(Values)
count

9